# Generated by Django 3.0.5 on 2021-03-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='question_type',
            field=models.IntegerField(choices=[(0, 'Multiple Choice'), (1, 'Open Ended')], default=1),
        ),
    ]
